### ISSUE TITLE
Dos it suppo for msm8953 (sdm625)?

### ISSUE THREAD

**Issue by bzy-080408** [msm8916-mainline/qhypstub#10]
I have a msm8953 device and I want to enable KVM on it.I have a kernel with KVM module builded.But I have not finished lk1st build,the drive have some bug.

**Comment by stephan-gh** [comment]
See https://github.com/msm8916-mainline/qhypstub/issues/4

**Comment by bzy-080408** [comment]
I funded a source at hier :https://gitlab.com/qcom-sources15/sources there have some leaked source,but none of msm8953.And how to use this source port for msm8974

**Comment by bzy-080408** [comment]
My Englisch is very bad,so....you maybe not understand.

**Comment by stephan-gh** [comment]
We're not interested in leaked source code here so please do not post such links. The basic approach of qhypstub does not work on MSM8953 and MSM8974 because they do not have a separate `hyp` (hypervisor) firmware that could be replaced.

You would need to modify the original Qualcomm firmware to get EL2 on those platforms.

Additionally, for MSM8974: The Krait CPU cores do not support virtualization at all as far as I know. Sorry.

**Comment by bzy-080408** [comment]
BTW does it support for msm8939v2(sdm616)?
I want to buy a phone to try this.

**Comment by stephan-gh** [comment]
MSM8939v2 is pretty much the same as MSM8939, so yeah qhypstub should work there.

**Comment by bzy-080408** [comment]
> MSM8939v2 is pretty much the same as MSM8939, so yeah qhypstub should work there.

Ok. test success.thanks
